# production:
#   type: deploy
#   script:
#   - gem install dpl
#   - cd api
#   - dpl --provider=heroku --app=moisture-track --api-key=$HEROKU_API_KEY
#   - cd ..
#   - cd frontend
#   - dpl --provider=heroku --app=moisture-track-fe --api-key=$HEROKU_API_KEY
