export const FETCH_PLANTS = "FETCH_PLANTS";
export const NEW_PLANT = "NEW_PLANT";
export const DELETE_PLANT = "DELETE_PLANT";
export const SELECT_PLANT = "SELECT_PLANT";

export const AUTH_USER = "AUTH_USER";

export const SET_CURRENT_MODAL = "SET_CURRENT_MODAL";
export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";
