export const AUTH_USER = "AUTH_USER";

export const SET_CURRENT_MODAL = "SET_CURRENT_MODAL";
export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";

export const FETCH_ALL_PLANTS_AND_GARDENS = "FETCH_ALL_PLANTS_AND_GARDENS";