export const AuthConsts = {
	GET_TOKEN: "GET_TOKEN"
}

export const ModalConsts = {
	SET_CURRENT_MODAL: "SET_CURRENT_MODAL",
	SET_MODAL_VISIBILITY: "SET_MODAL_VISIBILITY",
	SET_MODAL_WRAPPER_STATE: "SET_MODAL_WRAPPER_STATE"
}

export const OverviewConsts = {
	GET_ALL_LOADING: "OVERVIEW_GET_ALL_LOADING",
	GET_ALL_SUCCESS: "OVERVIEW_GET_ALL_SUCCESS",

	REMOVE_ITEM: "OVERVIEW_REMOVE_ITEM"
}

export const PageConsts = {
	GET_SELF_LOADING: "PAGE_GET_SELF_LOADING",
	GET_SELF_SUCCESS: "PAGE_GET_SELF_SUCCESS",
	GET_SELF_FAILURE: "PAGE_GET_SELF_FAILURE",

	GET_MEASUREMENTS_LOADING: "PAGE_GET_MEASUREMENTS_LOADING",
	GET_MEASUREMENTS_SUCCESS: "PAGE_GET_MEASUREMENTS_SUCCESS",
	GET_MEASUREMENTS_FAILURE: "PAGE_GET_MEASUREMENTS_FAILURE",
}

export const RecordableConsts = {
	CREATE_LOADING: "CREATE_RECORDABLE_LOADING",
	CREATE_SUCCESS: "CREATE_RECORDABLE_SUCCESS",
	CREATE_FAILURE: "CREATE_RECORDABLE_FAILURE",

	DELETE_LOADING: "DELETE_RECORDABLE_LOADING",
	DELETE_SUCCESS: "DELETE_RECORDABLE_SUCCESS",
	DELETE_FAILURE: "DELETE_RECORDABLE_FAILURE",

	EDIT_LOADING: "EDIT_RECORDABLE_LOADING",
	EDIT_SUCCESS: "EDIT_RECORDABLE_SUCCESS",
	EDIT_FAILURE: "EDIT_RECORDABLE_FAILURE",
}